Vérification de la taille des description
betagouv/publicodes-aides-velo pull request #31
Opened 2024-12-24 09:00 UTC by jenovateurs

Limité à 420 pour cette première itération et pour un souci d'uniformisation de la charte éditoriale.

2024-12-31 16:50 UTC, EmileRolley requested changes
Salut @jenovateurs,

Après réflexion je ne pense pas que la taille des descriptions devrait un changement cassant. En effet, il pourrait s'avérer nécessaire d'avoir une description un peu plus longue permettant d'expliquer plus en détails des changements ou autres. Libre ensuite à chaque réutilisateur:ice de choisir la façon dont il souhaite afficher les descriptions (ex: écraser certaines qui seraient trop longue, les rogner dynamiquement, etc...).

Ceci étant dit, je pense pas que pour l'instant il y ait une description en particulier qui nécessiterait de revenir en arrière sur les modifications proposées. Donc ça me va de les merger en l'état afin que vous puissiez enfin mettre en ligne les nouvelles aides. En revanche, je suis pour ne pas rajouter la contrainte dans les tests. On pourrait imaginer rajouter un warning pour les descriptions qui risqueraient d'être longues sans raisons.

N'hésites pas à me contredire si tu trouves une raison pour rajouter la contrainte :)

2025-01-01 09:10 UTC, jenovateurs commented
> Salut @jenovateurs,
> 
> Après réflexion je ne pense pas que la taille des descriptions devrait un changement cassant. En effet, il pourrait s'avérer nécessaire d'avoir une description un peu plus longue permettant d'expliquer plus en détails des changements ou autres. Libre ensuite à chaque réutilisateur:ice de choisir la façon dont il souhaite afficher les descriptions (ex: écraser certaines qui seraient trop longue, les rogner dynamiquement, etc...).
> 
> Ceci étant dit, je pense pas que pour l'instant il y ait une description en particulier qui nécessiterait de revenir en arrière sur les modifications proposées. Donc ça me va de les merger en l'état afin que vous puissiez enfin mettre en ligne les nouvelles aides. En revanche, je suis pour ne pas rajouter la contrainte dans les tests. On pourrait imaginer rajouter un warning pour les descriptions qui risqueraient d'être longues sans raisons.
> 
> N'hésites pas à me contredire si tu trouves une raison pour rajouter la contrainte :)

Bonjour @EmileRolley et bonne année 2025 à toi.
Janvier rime toujours avec de grosses mises à jour des dispositifs, aides…
Donc, ma priorité n°1 pour Aides Jeunes est de pouvoir utiliser un module à jour des aides vélos.
Pour éviter d'allonger le nombre d'itérations, je te propose de passer en message warning, qui m'aideront de toute manière à raccourcir les descriptions.
De cette manière, je peux finaliser l'intégration du module, et ensuite on pourra rééchanger sur cette problématique éditoriale du nombre de caractères.

2025-01-01 09:43 UTC, EmileRolley commented
Bonne année à toi aussi :)

T'as proposition me convient. Je vais faire la release dans la journée 👍

2025-01-01 09:43 UTC, merged

2025-01-01 09:44 UTC, Shamzic commented
Une idée pour résoudre ce problème avec un entre-deux serait d'autoriser une description courte et une autre description plus libre, mais cela risque d'être redondant. 

Le warning me semble être un peu anecdotique car le problème persiste, mais pour le moment je suis ok de faire ainsi.